### ISSUE TITLE
Create Parse DB for PetPal

### ISSUE THREAD

**Issue by sbrshkappa** [PetPal/PetPal#1]
- [x] Create Parse DB
- [ ] Create the Tables and keys for each Table

**Comment by linghao2** [comment]
Table and key can be created on the fly.

        Parse.initialize(with: ParseClientConfiguration(block: { (configuration: ParseMutableClientConfiguration) in
            configuration.applicationId = "petpal-parse-id"
            configuration.server = "https://petpal-parse.herokuapp.com/parse"
        }))
