### ISSUE TITLE
Create new property profile picture for user 

### ISSUE THREAD

**Issue by mr618show** [PetPal/PetPal#13]
User is able to upload profile pic to Parse and later be retrieved as thumbnail profile picture in different VCs.

**Comment by mr618show** [comment]
I uploaded several thumbnail pictures for each user in the Parse DB under class "User", when clicking on the file it shows the url as something like "http://petpal2.herokuapp.com/parse/files/petpal2-id/e44a11f62e9e5f0ccca3f10bc129cd06_user1.png". The question is how do I retrieve this part "e44a11f62e9e5f0ccca3f10bc129cd06_user1.png" programmatically to populate the thumnail picture in chatVC?

**Comment by sbrshkappa** [comment]
Here's and example of how to trim urls in Swift,


`var url = NSURL(string:"file:///Applications/App%20Store.app")
var lastComponent = url?.lastPathComponent
println("\(lastComponent)")
if lastComponent == "App Store.app" {
  println("Yes")
}`

**Comment by sbrshkappa** [comment]
@mr618show Did you already create the profile picture property in the DB or is this a proposed feature?

**Comment by mr618show** [comment]
Not yet. 

Hi, Sabareesh
I think you misunderstood my question or maybe I didn't explain clearly. The goal is to have the fullURL, which by definition fullURL = baseURL + imagePath. I was kind of reverse engineering to get the full URL: in the Parse DB if I click on the file, it will open up another tab where i can see the whole URL ""http://petpal2.herokuapp.com/parse/files/petpal2-id/e44a11f62e9e5f0ccca3f10bc129cd06_user1.png". From there I can tell the base is: http://petpal2.herokuapp.com/parse/files/petpal2-id/, the next is how to get the last part of it.   It will be even better if I can retrieve the whole thing programmatically. Say now each user has an image file in Parse DB,  in the ChatVC, how can I load each message with its owner's userProfileImage ?

**Comment by linghao2** [comment]
Tim has a tutorial on how to get display the image from Parse: https://guides.codepath.com/ios/Building-Data-driven-Apps-with-Parse#displaying-images-via-pfimageview

**Comment by mr618show** [comment]
Ling, thanks for the pointer! I will give it a try.

**Comment by mr618show** [comment]
![image](https://cloud.githubusercontent.com/assets/11971765/25595469/bc542610-2e79-11e7-871d-ff349f062d91.png)

retrieving works, still have to figure out how to upload programmatically. This will be needed when a user signs up.
