### ISSUE TITLE
Create Home View Controller

### ISSUE THREAD

**Issue by sbrshkappa** [PetPal/PetPal#2]
Create a basic home screen for the PetPal App based on the design document

**Comment by mr618show** [comment]
Just to clarify, the homeViewController is the loginViewController right?

**Comment by sbrshkappa** [comment]
@mr618show No, the home view controller is what the user sees after they login. It's the first page they see. Sort of like what 'Home' meant in the twitter app.

**Comment by linghao2** [comment]
Home view is deferred until next sprint.

**Comment by sbrshkappa** [comment]
Moving to Sprint 2.

**Comment by linghao2** [comment]
Don't need home anymore
