### ISSUE TITLE
Add Location Information on Sign Up

### ISSUE THREAD

**Issue by sbrshkappa** [PetPal/PetPal#20]
Get location information in the background during signup.

**Comment by sbrshkappa** [comment]
Considering adding the GeoLocation information to the User only when going into the nearbyGroups View.

**Comment by sbrshkappa** [comment]
@linghao2 Let me know if you think that's a good idea.

**Comment by linghao2** [comment]
Yes, I think so. Is there an option to use the more generalized location like a city?

**Comment by sbrshkappa** [comment]
@linghao2 Yeah, I spoke with Rui regarding this. It looks like there is a way in the GeoCoder Pod that she's using to reverse GeoCode from LatLong to a Physical Address. She is going to look into that.

**Comment by sbrshkappa** [comment]
Added
