### ISSUE TITLE
Create MessagesVC to show a list current conversations the current user is involved

### ISSUE THREAD

**Issue by mr618show** [PetPal/PetPal#25]
By tapping each conversation, it segues to ChatVC which opens up the current conversation.

**Comment by mr618show** [comment]
- Remove the duplicated conversation with the same userId in Message view
- Contact book which user can select the person he wants to chat with
- [optional] show the timestamp of last message in one conversation 
- [optional] show a count of the new/unread messages in a conversation

**Comment by sbrshkappa** [comment]
This is more or less done. the User's name still needs to be shown.

**Comment by mr618show** [comment]
All 4 items are completed.
